### ISSUE TITLE
undefined method each with faraday 0.16.2

### ISSUE THREAD

**Issue by bpieck** [gocardless/gocardless-pro-ruby#53]
Hi,

I think the version lock of faraday has to be changed. With faraday 0.15.4 everything works fine. On 0.16.2 I get following error:

/Users/bente/.gem/ruby/2.5.1/gems/faraday-0.16.2/lib/faraday/options.rb:52:in `merge!': undefined method `each' for nil:NilClass (NoMethodError)

with following backtrace:

```
	 6: from /Users/bente/projects/brandnooz/brandnooz-admin/config/initializers/active_merchant.rb:53:in `new'
	 5: from /Users/bente/.gem/ruby/2.5.1/gems/gocardless_pro-2.9.0/lib/gocardless_pro/client.rb:101:in `initialize'
	 4: from /Users/bente/.gem/ruby/2.5.1/gems/gocardless_pro-2.9.0/lib/gocardless_pro/client.rb:101:in `new'
	 3: from /Users/bente/.gem/ruby/2.5.1/gems/gocardless_pro-2.9.0/lib/gocardless_pro/api_service.rb:26:in `initialize'
	 2: from /Users/bente/.gem/ruby/2.5.1/gems/faraday-0.16.2/lib/faraday.rb:83:in `new'
	 1: from /Users/bente/.gem/ruby/2.5.1/gems/faraday-0.16.2/lib/faraday/options.rb:67:in `merge'
```

**Comment by bpieck** [comment]
Ok, my first impression was, I needed a downgrade of faraday.
But it seems, that it is working with faraday 0.17.0 again. So most probable it is no issue in version lock here - but on faraday itself.

**Comment by nickcampbell18** [comment]
Faraday 0.16 strikes again. Shall we push a change to require `~> v0.17`?

**Comment by dmagliola** [comment]
I think this is probably superseded by #57 , so i'm closing this issue. Feel free to re-open if you disagree
